### ISSUE TITLE
Feature Request: GitHub page

### ISSUE THREAD

**Issue by Foso** [BenjaminRi/Banania#3]
Thank you for this port. I'm a fan of the original and played it over and over again :) 

I tried creating a Banania port in Java years ago, but i failed on implementing the enemies ^^

I just had the idea, that hosting your game on a GitHub page would be an easy way
for other people, that find this repo, to play it

**Comment by BenjaminRi** [comment]
Hi @Foso ,

Currently, I have no plans to set up GitHub Pages. However, you're right in pointing out that the repository is missing a link to play the game online. I have a personal website on which [Banania can be played](https://mental-reverb.com/creations/banania/banania.html). I added links to my website and the Internet Archive in the Readme.

> I tried creating a Banania port in Java years ago, but i failed on implementing the enemies ^^

I implemented the enemy logic by playing the game and inspecting videos to understand their behaviour. I also exchanged some emails with Rüdiger Appel on the subject, however, he didn't remember the gritty details of the movement logic. To do it perfectly, one would have to reverse engineer the assembly code. Although I recently started reversing games with Ghidra, reversing such a large part of the code would be an arduous task. My implementation is only an approximation. So I understand how you can get stuck on that part.
